### ISSUE TITLE
CTD shift-clicking output of the sawbench

### ISSUE THREAD

**Issue by xenoflot** [gcewing/ArchitectureCraft#10]
While testing the "eats all the input" bug, I rapid-clicked on the output slot and saw the stack in hand growing as expected. Then I held down shift and time stopped...

http://pastebin.com/r21tct6A

architecturecraft 1.5.1
mc 1.10.2
forge 2122

Time: 11/8/16 8:37 PM
Description: Updating screen events

java.lang.StackOverflowError: Updating screen events
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:555)
	at net.minecraft.item.ItemStack.func_150996_a(ItemStack.java:947)
	at net.minecraft.item.ItemStack.<init>(ItemStack.java:96)
	at net.minecraft.item.ItemStack.func_77946_l(ItemStack.java:356)

**Comment by xenoflot** [comment]
Tried it a second time, same result. Shift-clicking a 1/4 round of cobble.

**Comment by xenoflot** [comment]
CTD shift-clicking from the input slot as well.

**Comment by gcewing** [comment]
xenoflot wrote:

> CTD shift-clicking from the input slot as well.

This should work too -- is there a problem?

## 

Greg

**Comment by xenoflot** [comment]
Using the file versions listed above, I assure you that shift-left-clicking on either the input or output slots of the sawbench results in a crash to the desktop with the linked crash log.

Perhaps it's a cross-mod issue? Our pack is here if you can't reproduce the fault: http://www.technicpack.net/modpack/sssserverpack-quite-unstable.912983

**Comment by gcewing** [comment]
xenoflot wrote:

> Using the file versions listed above, I assure you that 
> shift-left-clicking on either the input or output slots of the sawbench 
> results in a crash to the desktop with the linked crash log.

This should work in 1.6.0 or later.

## 

Greg

**Comment by xenoflot** [comment]
Confirmed working fine in SSP and SMP with 1.7.0-mc1.10.2

Thanks!
