### ISSUE TITLE
[Request] Ability to use Chiselled Bits as source material

### ISSUE THREAD

**Issue by xenoflot** [gcewing/ArchitectureCraft#16]
Sick of me yet? :-) Your mod is a big hit with the creative types on our server, so it's getting a workout!

I'm not sure if it's even possible, but a player asked me tonight if it was possible to use a block from Chisels and Bits as a source block for Architecture Craft. I tested, it wasn't.  It'd be awesome if we could!

Cheers

**Comment by gcewing** [comment]
xenoflot wrote:

> a player asked me tonight if it 
> was possible to use a block from Chisels and Bits as a source block for 
> Architecture Craft.

I don't even know what you would expect that to do.
Can you elaborate?

## 

Greg

**Comment by xenoflot** [comment]
Sorry I wasn't clear. Aside from it's value as a sculptural tool, C&B is also commonly used (at least on my server) to create custom decoration blocks. 

Just as we can currently put a piece of cobblestone, wood or whatever in the sawbench and create roof tiles, arches or whatever, it would be nice to be able to take a block created with C&B and create architecture blocks from it.

**Comment by gcewing** [comment]
xenoflot wrote:

> Just as we can currently put a piece of cobblestone, wood or whatever in 
> the sawbench and create roof tiles, arches or whatever, it would be nice 
> to be able to take a block created with C&B and create architecture 
> blocks from it.

Ah, I think I see what you mean. You want to use a C&B block
as a pattern, and create AC blocks having the same shape?

That's an interesting idea, although I'm not sure whether
it would be feasible at the moment. I have my own ideas on
how to allow creating custom block shapes. Maybe it could
be made part of that, we'll see.

## 

Greg

**Comment by trevorjd** [comment]
Yep, steal the texture from the C&B block to wrap around an AC block.

The inspiration for this was wanting to put glass inside an arch. After posting, I realised that wouldn't be possible, but being able to use C&B blocks for textures would still be cool.

Incidentally, if you're feeling bored and it's technically possible... having a 2nd input slot on the sawbench for the "fill" texture would be awesome. For example, having a cobblestone arch filled with glass would make for some awesome windows!

**Comment by xenoflot** [comment]
Yep, steal the texture from the C&B block to wrap around an AC block.

The inspiration for this was wanting to put glass inside an arch. After posting, I realised that wouldn't be possible, but being able to use C&B blocks for textures would still be cool.

Incidentally, if you're feeling bored and it's technically possible... having a 2nd input slot on the sawbench for the "fill" texture would be awesome. For example, having a cobblestone arch filled with glass would make for some awesome windows!

**Comment by gcewing** [comment]
Trevor Dickson wrote:

> Yep, steal the texture from the C&B block to wrap around an AC block.

But "steal the texture" doesn't make sense for a C&B block,
because it's not just a block with a texture applied, it's
a shape of its own. I haven't seen how C&B is implemented,
but I'm guessing that there isn't any texture to steal
other than the textures of the original materials it's
made from.

> The inspiration for this was wanting to put glass inside an arch.

I sympathise. I've been thinking about providing arched
windows as a block type, but you would really want _three_
textures -- the arch, the frame and the glazing. At which
point it becomes clear that AC really wants do be a
microblock system. Which will probably happen at some
point, when I figure out the best way to go about it.

## 

Greg

**Comment by xenoflot** [comment]
> "steal the texture" doesn't make sense for a C&B block,

It does if you have a (more or less) full block. Yes, depending on how C&B implements it, it may not even be possible. Just a nice to have if you can find a way to do it.

Thanks for considering. I'll leave you to implement or not as you desire!
