### ISSUE TITLE
AC Blocks turning into Roof Tile

### ISSUE THREAD

**Issue by NielsPilgaard** [gcewing/ArchitectureCraft#21]
I have no crash log or the like, as this is not a crash.

Every once in a while, the Architecturecraft blocks I have placed, turn into Roof Tiles with the Oak Plank texture. So far it has happened to slabs with chiseled Jungle Planks, and pillars/pillar caps with Stone Brick texture.

**Comment by NielsPilgaard** [comment]
![2017-03-02_18 03 20](https://cloud.githubusercontent.com/assets/21295394/23518127/b8543ca2-ff72-11e6-863c-6ff4b17d805d.png)

**Comment by miiichael** [comment]
I see this occasionally too. Disconnecting from the server and reconnecting is usually enough to fix it (until next time of course :stuck_out_tongue:) so it's almost certainly a client-side issue. Forge 1.12.2-14.23.5.2795, AC 1.12-3.80 (plus a bunch of other mods including troublemakers optifine and IE). It unfortunately (or fortunately) happens too rarely to work out how to reproduce it. :grimacing: 
![2019-01-10_23 48 39](https://user-images.githubusercontent.com/4179353/55168035-06653980-51ad-11e9-9267-c82832cbdd5a.png)

**Comment by NielsPilgaard** [comment]
It hasn't happened for me in a long time, I guess I'll close this issue.

**Comment by miiichael** [comment]
Hey, where'd my wall go?
![2019-05-05_13 57 01](https://user-images.githubusercontent.com/4179353/57189205-0f7cbf80-6f3e-11e9-9dd8-d2a36fbf4707.png)

Oh, the weird and rare AC rendering bug is back.
![2019-05-05_13 57 22](https://user-images.githubusercontent.com/4179353/57189204-0f7cbf80-6f3e-11e9-8c2a-7d72067c9735.png)

It happens sufficiently rarely that I'm not inclined to reopen the bug just yet (particularly given everyone hates debugging problems that could potentially be optifine's fault :P), but wanted to make a note that it still happens.

It may help to note that the invisible pieces reappear as wooden slopes when they're interacted with (eg. directly within WAWLA range, or walking adjacent to them).

Forge 14.23.5.2808, AC 1.12-3.80 (which is reporting in-game as version `@VERSION@`, BTW), Wawla 1.12.2-2.5.269, Optifine 1.12.2_HD_U_E4 pre1.

**Comment by NielsPilgaard** [comment]
The issue also happens without Optifine.
