### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by Chemiefreak2006** [gcewing/ArchitectureCraft#22]
[http://pastebin.com/V93teDSH](url)

**Comment by gcewing** [comment]
Chemiefreak2006 wrote:
> http://pastebin.com/V93teDSH <url>

What were you doing when this happened?

-- 
Greg

**Comment by Chemiefreak2006** [comment]
I had just placed some Arches out of chiseled stone and was walking back to the crafting table. Then the client crashes. It keeps doing that every time I try logging in...

Greetings from Berlin

**Comment by Chemiefreak2006** [comment]
Any idea how to work around this problem so I can log in and play again?

**Comment by gcewing** [comment]
Chemiefreak2006 wrote:
> Any idea how to work around this problem so I can log in and play again?

Not at the moment, sorry. I'm working on some changes that
might make it more robust against this kind of thing, but
it could take a while. All I can suggest in the meantime
is to restore the world from an earlier backup.

-- 
Greg

**Comment by gcewing** [comment]
Addressed in version 1.7.3.
