### ISSUE TITLE
RenderCrash with YeOldBarrel

### ISSUE THREAD

**Issue by Speiger** [gcewing/ArchitectureCraft#26]
ArchitectureCrafts renderOverride causes a RenderCrash in YeOldBarrel.

https://github.com/shadowfacts/YeOldeTanks/issues/27

Thats the post i opened. I can provide further information if needed

**Comment by gcewing** [comment]
You should report this to Chisel & Bits. Although I don't think this
one is AC-related, I've had reports of Chisel & Bits interacting
badly with AC, resulting in similar symptoms -- a crash due to a
tile entity that's missing or of the wrong type.

-- 
Greg

**Comment by gcewing** [comment]
Reported fixed in YeOldeTanks.
