### ISSUE TITLE
Crash with Optifine

### ISSUE THREAD

**Issue by NielsPilgaard** [gcewing/ArchitectureCraft#27]
Hey!

I wasn't sure where to post this crashlog to be honest, as it's caused by Optifine, but I thought it couldn't hurt to post it here.

The issue is, a member of my server crashes when he gets near Spruce Shelves. It doesn't happen without Optifine. Here's the crashlog: https://pastebin.com/aCRMwhDT

**Comment by gcewing** [comment]
I don't think this is an AC problem, but in any case, your warranty is void if you use AC with Optifine.

**Comment by NielsPilgaard** [comment]
Ugh, I posted this on the wrong git, sorry for the inconvinience.
