### ISSUE TITLE
Duplication Bug - Destroying Item With Cladding Returns Cladding Source Block

### ISSUE THREAD

**Issue by Sporkley** [gcewing/ArchitectureCraft#3]
This bug has the potential to turn any block that can be applied as a cladding into 16 of that block, a major duplication bug.  Issue detected in mc versions 1.7.10 and 1.8.9

Reproduction:
1. Place a roof tile in the world
2.  Create 16 cladding items on the sawbench using a valuable block (i.e. Block of Diamond). 
3.  Apply cladding to roof tile
4. Destroy roof tile.  You will receive the roof tile and the original item that created the cladding (i.e. Block of Diamond)

**Comment by Dijkstra1-zz** [comment]
Do not if the [mod pack](https://mods.curse.com/modpacks/minecraft/242462-all-the-mods) that i am playing, is using old version or this mod or it not fixed.
