### ISSUE TITLE
[Crash] [1.7.1-mc1.10.2] - Client crash on joining the server.

### ISSUE THREAD

**Issue by JaSpr** [gcewing/ArchitectureCraft#31]
We updated our FTB Beyond server from 1.6.1 to 1.7.0 today, and I did the same with my client.  After updating, I attempted to join the server, and the client crashed.  I restarted the client, tried again, and got the same result.

[Crash report.](https://gist.github.com/JaSpr/9c09bc3962262203b723c5c3a65dba89)

The error is ```java.lang.ArrayIndexOutOfBoundsException: -117``` and references ```gcewing.architecture.BaseAORenderingManager$CustomBlockRendererDispatcher.func_175018_a(BaseAORenderingManager.java:85)```

**Comment by gcewing** [comment]
This seems to be a Thermal Expansion problem, I suggest reporting it to them.
